version: '3.0'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATA_DIRECTORY: ${DATA_DIRECTORY}
      CHROMA_PERSIST_DIRECTORY: ${CHROMA_PERSIST_DIRECTORY}
    # volumes:
    #   - ../goinfre:/goinfre
    ports:
      - 8080:8080
